### ISSUE TITLE
TypeError: Cannot read property 'charAt' of undefined

### ISSUE THREAD

**Issue by ntdat247** [cryptosharks131/NiceNOMP#1]
I got errors when run pool:
[2018-08-03T21:31:28.974Z] [info] [system] [CLI] : CLI listening on 127.0.0.1:17120
[2018-08-03T21:31:29.532Z] [info] [system] [Website] : Starting Website module
[2018-08-03T21:31:29.536Z] [info] [system] [Stats] : Starting Stats Module...
[2018-08-03T21:31:29.536Z] [debug] [system] [Stats] : Initializing Stats Redis...
[2018-08-03T21:31:29.540Z] [debug] [system] [Stats] : Initializing Stats History...
[2018-08-03T21:31:29.576Z] [info] [system] [Website] : Website started on 0.0.0.0:8889

undefined:3
var out='<style>\n  #bottomNotes {\n    display: block;\n    padding-left: 18px;\n    padding-right: 18px;\n    padding-bottom: 18px;\n  }\n\n  #topPool {\n    padding-top: 18px;\n    padding-left: 18px;\n    padding-right: 18px;\n  }\n\n  #topPool>div>div>svg {\n    display: block;\n    height: 280px;\n  }\n\n  .poolWrapper {\n    border: solid 1px #c7c7c7;\n    border-radius: 5px;\n    padding: 5px;\n    margin-bottom: 18px;\n  }\n\n  .poolLabel {\n    font-size: 1.2em;\n    text-align: center;\n    padding: 4px;\n  }\n\n  .poolMinerTable {}\n\n  table {\n    width: 100%;\n  }\n</style>\n<div style="margin-top: 36px;" >\n  '; var sortedPools = Object.keys(it.stats.pools); out+='\n  '; sortedPools.sort(function(a, b) { return a.workerCount - b.workerCount; }); out+='\n  <div class="col-md-5 table-responsive">\n    <table class="table table-bordered">\n      <thead>\n        <tr>\n          <th><i class="fa fa-history"></i> Block History For</th>\n         ` <th>`\n            <select class="form-

TypeError: Cannot read property 'charAt' of undefined
    at Object.eval [as blocks] (eval at doT.template (/root/NiceNOMP/node_modules/dot/doT.js:133:11), <anonymous>:3:1268)
    at processTemplates (/root/NiceNOMP/libs/website.js:62:62)
    at /root/NiceNOMP/libs/website.js:93:13
    at /root/NiceNOMP/node_modules/async/dist/async.js:473:16
    at iteratorCallback (/root/NiceNOMP/node_modules/async/dist/async.js:1064:13)
    at /root/NiceNOMP/node_modules/async/dist/async.js:969:16
    at /root/NiceNOMP/libs/website.js:86:17
    at tryToString (fs.js:513:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:501:12)

**Comment by TheRealHotSwap** [comment]
same issue here.

**Comment by cryptosharks131** [comment]
What was happening when this occurred?  Did you find and pay any blocks successfully?

**Comment by cryptosharks131** [comment]
This is likely due to not properly configuring all the config files.  These 3 files needs to be properly set.

1. config.json in pool folder
2. coin.json in pool_configs folder
3. coin.json in coins folder

**Comment by 88plug** [comment]
This is easy one to solve - make sure you have enabled coins and pool_configs correctly!
